### ISSUE TITLE
Help on usage

### ISSUE THREAD

**Issue by rainecc** [mikestead/swagger-routes#2]
Hi, really liking this library too, been looking for something to allow me to do some specific route handling in node express from a swagger file.

Use case: **add the tag name to the route handler**
It looks like the handlerfactory approach would work well for this, but the examples are a little above my understanding. Could you help me work out what a handler might look like for this case?

api.yaml: parameters and other stuff omitted for brevity
```yaml
  /authtest/{id}:
    get:
      x-method-id: "1022"
      tags:
      - "system"
  post:
      x-method-id: "1023"
      tags:
      - "system"
```
required handler folder structure for both of these would be 

    /routes/system/authtest,js

methods in that handler would be 

    authtestPOST(req, res, next)
    authtestGET(req, res, next)

And the x-method-id needs to be parsed and available in the request somewhere.

**Comment by mikestead** [comment]
@rainecc thanks for the interest. Hopefully I can answer your questions.

Both of these answers require `swagger-routes 1.4+`.

## Option 1

So the easiest path you could take which would get you close to what you wanted, with the benefit of file generation, is the following.

Given your swagger spec including the fragment below.

``` yaml
...
paths:
  /authtest/{id}:
    get:
      x-method-id: "1022"
      operationId: authtestGET
      tags:
        - system
    post:
      x-method-id: "1023"
      operationId: authtestPOST
      tags:
        - system
```

And  `index.js`

``` javascript
const swaggerRoutes = require('swagger-routes')
const express = require('express')
const app = express()

swaggerRoutes(app, {
	api: './api.yml',
	handlers: {
		path: './routes',
		group: true
	}
})

app.listen(8080);
```

When run the above would generate handlers with the following paths

    ./routes/system/authtestGET.js
    ./routes/system/authtestPOST.js

Then inside each of these handlers you can access the operation info e.g.

```
exports.handler = function authtestGET(req, res, next) {
  console.log(req.operation['x-method-id'])
  res.send('authtestGET')
}
```

## Option Two

The first option is nice as there's a little more automation, however you can get closer to what you requested doing the following.

``` yaml
...
paths:
  /authtest/{id}:
    x-serviceId: authtest
    get:
      x-method-id: "1022"
      operationId: authtestGET
      tags:
        - system
    post:
      x-method-id: "1023"
      operationId: authtestPOST
      tags:
        - system
```
Notice the added `x-serviceId` above.

``` javascript
const swaggerRoutes = require('swagger-routes')
const express = require('express')
const app = express()

swaggerRoutes(app, {
	api: './api.yml',
	handlers: createHandler
})

function createHandler(operation) {
	return function handler(req, res, next) {
		const serviceId = operation['x-serviceId']
		const modulePath = `./routes/${operation.pkg}/${serviceId}.js`
		// 'require' will throw if the file doesn't exist so you need to create or create it yourself
		const service = require(modulePath)
		const handler = service[operation.id]
		if (typeof handler === 'function') {
			handler(req, res, next)
		} else {
			res.sendStatus(404)
		}
	}
}

app.listen(8080);
```

So given the file

    ./routes/system/authtest.js

With handler functions inside like

```
exports.authtestGET = function authtestGET(req, res, next) {
  console.log(req.operation['x-method-id'])
  res.send('authtestGET')
}
```
You should be set.

One side point. I'd always try and keep the RESTful terminology out of your `operationIds` (e.g. don't add GET or POST to the name). When it comes to code generation for client or server, the code will read better and if you need to refactor to a different http method later you won't break any code.

Did that answer your questions ok?
