### ISSUE TITLE
formData required validation

### ISSUE THREAD

**Issue by fabricio-godoi** [mikestead/swagger-routes#26]
Greetings everyone, 
I'm having problem when validation formData file upload with multer and swaggerRoutes.
swagger.yml

```
parameters:
- in: "formData"
        type: "file"
        required: true
        name: "document"
```

The swaggerRoutes method returns this when validating the "required: true":
` "message": "formData requires property \"document\""`

If I set required as false, the swaggerRotues continues without any problem.

Anyone have any ideas how to solve this?
