### ISSUE TITLE
Array items failing validation

### ISSUE THREAD

**Issue by rainecc** [mikestead/swagger-routes#8]
yaml definition
```javascript
testarray:
  type: "array"
  items:
    type: "integer"
    format: "int64"
```

sending this data in the body:

`testarray: [1,5,9]`

-or- 

`testarray: 1,5,9`

returns this error: 

```body.testarray[0] is not of a type(s) integer, body.testarray[1] is not of a type(s) integer, body.testarray[2] is not of a type(s) integer```

Of course, it may well be the format I am sending...

**Comment by mikestead** [comment]
It's a little hard to debug without seeing your parameter definition, but if you want `testarray` to be a property of the body then your schema should define the body as an object e.g.

```yaml
# under 'paths'
/numbers:
  post:
    operationId: submitArray
    parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/SubmitArray'
...
```

```yaml
# Under 'definitions'
SubmitArray:
  type: object
  properties:
    testarray:
      type: array
      items:
        type: integer
        format: int64
```
